"""content models

Revision ID: ccea996c05f3
Revises: 6deaf8073b35
Create Date: 2026-05-20 21:35:27.002509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccea996c05f3'
down_revision = '6deaf8073b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=512), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_key'), ['key'], unique=True)

    op.create_table('crew_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('portrait_url', sa.String(length=1024), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('entry_no', sa.String(length=16), nullable=False),
    sa.Column('tilt', sa.String(length=8), nullable=False),
    sa.Column('accent', sa.String(length=8), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('crew_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crew_members_sort_order'), ['sort_order'], unique=False)

    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=1024), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_status'), ['status'], unique=False)

    op.create_table('merch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('price_display', sa.String(length=32), nullable=False),
    sa.Column('external_url', sa.String(length=1024), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_name', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('bandcamp_url', sa.String(length=1024), nullable=True),
    sa.Column('spotify_url', sa.String(length=1024), nullable=True),
    sa.Column('apple_music_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('hero_image_url', sa.String(length=1024), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_slug'), ['slug'], unique=True)

    op.create_table('press_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scuttlebutts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=1024), nullable=True),
    sa.Column('accent', sa.String(length=8), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_quote', sa.Text(), nullable=False),
    sa.Column('hero_image_url', sa.String(length=1024), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('footer_text', sa.Text(), nullable=False),
    sa.Column('ports_visited', sa.Integer(), nullable=False),
    sa.Column('grog_pints', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tour_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tour_dates_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_dates_status'), ['status'], unique=False)

    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('caption', sa.String(length=512), nullable=False),
    sa.Column('alt_text', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery_images')
    with op.batch_alter_table('tour_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_dates_status'))
        batch_op.drop_index(batch_op.f('ix_tour_dates_starts_at'))

    op.drop_table('tour_dates')
    op.drop_table('site_settings')
    op.drop_table('scuttlebutts')
    op.drop_table('press_assets')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_posts_published_at'))

    op.drop_table('posts')
    op.drop_table('music_tracks')
    op.drop_table('merch_items')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiries_status'))
        batch_op.drop_index(batch_op.f('ix_inquiries_kind'))
        batch_op.drop_index(batch_op.f('ix_inquiries_created_at'))

    op.drop_table('inquiries')
    op.drop_table('galleries')
    with op.batch_alter_table('crew_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crew_members_sort_order'))

    op.drop_table('crew_members')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_key'))

    op.drop_table('assets')
    # ### end Alembic commands ###
